[package]
name = "cerebrust"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.3", features = ["rfcomm", "bluetoothd"] }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
